### ISSUE TITLE
in regards to the 0.2.19 crash error code 1 compatibility issue.

### ISSUE THREAD

**Issue by hazerddex** [SodiumZH/Befriend-Mobs#2]
[latest.log](https://github.com/SodiumZH/Befriend-Mobs/files/13716966/latest.log)
[2023-12-18-6.log.gz](https://github.com/SodiumZH/Befriend-Mobs/files/13716968/2023-12-18-6.log.gz)

I couldn't locate any debug.txt

but I  booted up the game with the latest update with my modlist and got the latest.txt as well as one that seems to consist of random gibberish though not sure how much help it will be.

**Comment by SodiumZH** [comment]
This is probably because of Mixin-Extras version conflict and now I haven't found the exact reason. In 0.x.20 I'll upload an extra "-slim.jar" file which doesn't include Mixin-Extra jar inside and it may be fixed using it if not compatible.
